In [4]:
import numpy as np

In [14]:
l = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
arr = np.array(l)
print("Dimension:",arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)

Dimension: 2
Shape: (3, 4)
Size: 12


In [15]:
my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
first_row = my_array[0, :]
first_row

array([1, 2, 3, 4])

In [17]:
my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
a = my_array[2, 3]
a

12

In [18]:
odd_indexed_elements = my_array[:, 1::2].flatten()
odd_indexed_elements


array([ 2,  4,  6,  8, 10, 12])

In [21]:
mat = np.random.rand(3,3)
mat

array([[0.21179589, 0.38160155, 0.96894764],
       [0.48828935, 0.18393954, 0.74003579],
       [0.53912257, 0.47689689, 0.54536766]])

In [26]:
expanded_array = np.expand_dims(my_array, axis=2)
expanded_array

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [28]:
transposed_array = np.transpose(my_array)
transposed_array

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [29]:
matrix_A = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

matrix_B = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])


matrix_addition = matrix_A + matrix_B

matrix_multiplication = np.dot(matrix_A, matrix_B.T)

matrix_subtraction = matrix_A - matrix_B

matrix_division = np.divide(matrix_B, matrix_A)

print("Matrix Addition:")
print(matrix_addition)

print("\nMatrix Multiplication:")
print(matrix_multiplication)

print("\nMatrix Subtraction:")
print(matrix_subtraction)

print("\nMatrix Division:")
print(matrix_division)


Matrix Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix Division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
import numpy as np

# Create a sample array
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order
swapped_array = original_array.byteswap()

print("Original Array:")
print(original_array)

print("\nSwapped Array:")
print(swapped_array)


Original Array:
[1 2 3 4]

Swapped Array:
[16777216 33554432 50331648 67108864]


In [31]:
import numpy as np

# Create a 2x2 matrix
matrix_A = np.array([[4, 7],
                     [2, 6]])

# Calculate the inverse of the matrix
inverse_A = np.linalg.inv(matrix_A)

# Verify the result by multiplying the matrix with its inverse
identity_matrix = np.dot(matrix_A, inverse_A)

print("Original Matrix:")
print(matrix_A)

print("\nInverse Matrix:")
print(inverse_A)

print("\nProduct with Inverse (Should be Identity Matrix):")
print(identity_matrix)


Original Matrix:
[[4 7]
 [2 6]]

Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]

Product with Inverse (Should be Identity Matrix):
[[ 1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00]]


In [33]:

arr1d = np.array([1, 2, 3, 4, 5, 6])
arr2d = np.reshape(arr1d, (2, 3))
print(arr2d)



[[1 2 3]
 [4 5 6]]


In [34]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([10, 20, 30])
result = a + b
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]
